### ISSUE TITLE
在ios端缓存有点不稳定

### ISSUE THREAD

**Issue by chenhaigang888** [LinXunFeng/flutter_video_cache#2]
在ios端使用缓存的时候存在一些问题。当我播放短一点视频比较正常。但是我播放一个文件体积比较大的文件的时候，视频没有播放，而且检测网络发现没有链接网络。取消缓存后则可以正常播放。
测试设备：
iPhone 15 pro max  ios18
iPhone 8 plus   ios16.7.8
Android studio：Android Studio Koala | 2024.1.1 Patch 2
xcode ：Version 15.4 (15F31d)
flutter：3.24.0

**Comment by LinXunFeng** [comment]
`iOS` 端依赖的缓存库是 [ChangbaDevs/KTVHTTPCache](https://github.com/ChangbaDevs/KTVHTTPCache)，遇到的缓存问题可向该库的作者反馈，如：https://github.com/ChangbaDevs/KTVHTTPCache/issues/25

**Comment by chenhaigang888** [comment]
我发现微信群的二维码失效了😂

**Comment by LinXunFeng** [comment]
可以添加二维码下方的群管理员，备注 “进群”，通过后会拉你入群。

不更新二维码的原因:
1. 微信公众号的文章有修改次数限制，也麻烦
2. 要做过滤，尽量避免有人混进去发垃圾消息

**Comment by chenhaigang888** [comment]
升级到最新版本的Android studio后编译报错：
环境：
Android Studio Koala Feature Drop | 2024.1.2
Build #AI-241.18034.62.2412.12266719, built on August 23, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 15.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 10
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.ankit.mahadik.json.dart.class (2.16)
  Dart (241.18808)
  io.flutter (82.0.2)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.danikula:videocache:2.7.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://repo.maven.apache.org/maven2/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://jcenter.bintray.com/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://www.jitpack.io/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
     Required by:
         project :app > project :video_cache

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 15s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by LinXunFeng** [comment]
打开 `android` 目录下的 `build.gradle`，补充下面两个 `maven`

```gradle
repositories {
    google()
    mavenCentral()
    maven{ url "https://maven.aliyun.com/repository/public" }
    maven{ url "https://jitpack.io" }
}
```

**Comment by chenhaigang888** [comment]
已经搞定了，多谢了
